title: lemonblog
author: liz-lemon
email: lizgemmiti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  opinion pieces, personal projects

# social links
twitter_username: lemmongemmon # DO NOT include the @ character, or else the build will fail!
github_username:  liz-lemon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
